### ISSUE TITLE
Mejoras en la entidad Medios de Pago

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.estetica.spring#13]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne`
correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo
siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la eliminación de un nuevo elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el
    controlador, debes incluir la referencia a su entidad (a diferencia
    de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.

  - *Utilidades del response*: utilizar el objeto ResponseEntity
    combinado con el objeto APIResponse. Utilizar la utilidad
    ResponseUtil.

  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando
    la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y
    detallando lo mejor posible el funcionamiento técnico de la
    siguiente parte del código:

Implementación del Servicio

  - Probar todos los métodos del controlador y hacer captura de pantalla
    de la evidencia obtenida. Esta evidencia debe ser incluida en los
    comentarios del pull request.

**Comment by Luis-Alberto-Espinoza** [comment]
### Buscar a todos 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/7d7250c0-f965-4f7b-b0a8-dd73859ba0d8)

---
### Buscar por id
En este caso se busca uno que existe que es el correspondiente al del id 1 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/21d327f8-3b3b-48f9-808f-530c04433702)


#### Buscar por id - caso Error!!
En este caso se busca por un id que no existe 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/b4ad745a-7ae1-48d3-ae86-b48a21cf33ec)

---
### Guardar un nuevo registro 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/29b72a22-9b21-44dd-a9a0-13b4c67e7b84)

corroboramos que fue ingresado a la base de datos y lo encontramos con el ID 13 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/3bc03436-d2a9-4c48-985d-9b5aee54c3b1)

---
### Actualizar un registro
Para este ejemplo se usa el registro recién ingresado que posee el ID 13
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/a82c89cd-c566-42a0-afce-0d4c444b01bb)

Se comprueba que haya sido modificado el registro con id 13
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/4ff2a3a0-6ce8-4a0d-98d9-679dd3665369)

#### Actualizar un registro que no exista en la BD
Se intenta actualizar un registro que no existe en la bd 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/9a6c51a6-7b04-4b8e-ae21-6371b0040841)

---
### Eliminacion 
para este ejemplo se eliminara el registro con el id 11 que si existe en la base de datos 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/9c9407e9-0650-4e7d-b49c-50079d4fc00d)

#### Eliminar un registro que no existe en la bd
Para este ejemplo se usará el registro con el ID 11 que en el ejercicio anterior ya fue borrado 
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/92590451/57aab3b2-46e7-4f31-a309-2988e683bf98)

**Comment by ahumadamob** [comment]
Muy bueno lo que venís haciendo hasta ahora. Fíjate por favor en el método delete porque en el momento que te devuelve una eliminación exitosa parece que no devuelve el formato correcto de la api response
