### ISSUE TITLE
Mejoras en la entidad Empleado

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.estetica.spring#14]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne`
correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo
siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la eliminación de un nuevo elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el
    controlador, debes incluir la referencia a su entidad (a diferencia
    de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.

  - *Utilidades del response*: utilizar el objeto ResponseEntity
    combinado con el objeto APIResponse. Utilizar la utilidad
    ResponseUtil.

  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando
    la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y
    detallando lo mejor posible el funcionamiento técnico de la
    siguiente parte del código:

Método `POST` en el controller

  - Probar todos los métodos del controlador y hacer captura de pantalla
    de la evidencia obtenida. Esta evidencia debe ser incluida en los
    comentarios del pull request.

  - Ajustar los siguientes elementos detectados en las anteriores
    issues:

EmpleadoController debe estar en el package controller en vez de controllers
Empleado debe estar en el package entity en vez de entities
Renombrar la interface a IEmpleadoService y moverlo al package service
La implementación debe llamarse EmpleadoServiceImplJpa y debe moverse al package service.jpa

**Comment by dev-NIK0** [comment]
**BUSCA TODOS LOS EMPLEADOS**
![get all](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/9452e82d-4bde-4d00-8234-9feea8c64f25)
**BUSCA AL EMPLEADO POR ID**
![get id](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/530a8574-b8cf-403b-803b-ca3fe7f4eafa)
**SE REALIZA UN CAMBIO EN UN EMPLEADO POR ID **
![put](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/073f29f0-ff37-462b-8eaf-0c09f3d8d709)
**SE CREA UN NUEVO  EMPLEADO**
![save](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/6c35da64-4e2d-4d9e-8794-e2b9acd61bf8)
**SE ELIMINA UN EMPLEADO**
![delete](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/903edad5-e4ce-4a9c-b460-d82b12212554)

**Comment by ahumadamob** [comment]
Debes realizar además las siguientes pruebas:
`GET` para buscar todos, en caso que no tengas registros en la tabla.
`GET` para buscar por id, pero con un id que no exista en la tabla.
`POST` enviando un id que si existe en la tabla.
`PUT` enviando un id que no existe en la tabla.
`DELETE` enviando un id que no existe en la tabla.

**Comment by dev-NIK0** [comment]
**GET PARA BUSCAR POR ID QUE NO EXISTE EN LA TABLA**
![get id error 2](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/d3e31a1e-4967-4ed6-88e3-ed5990a70f02)
**POST ENVIANDO UN ID QUE EXISTE EN LA TABLA**
![POST ERROR](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/fd8d0278-3906-4634-92c9-de24f5efaf25)
**PUT ENVIANDO UN ID QUE NO EXISTE EN LA TABLA**
![put id error](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/f315940d-aca8-4963-a057-0ca09821562e)
**DELETE ENVIANDO UN ID QUE NO EXISTE EN LA TABLA**
![delete error id](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/84420472/75aab92d-8f64-408e-ba11-59522e439e55)
