### ISSUE TITLE
Mejoras en la entidad Cliente

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.estetica.spring#15]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne`
correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo
siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la eliminación de un nuevo elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el
    controlador, debes incluir la referencia a su entidad (a diferencia
    de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.

  - *Utilidades del response*: utilizar el objeto ResponseEntity
    combinado con el objeto APIResponse. Utilizar la utilidad
    ResponseUtil.

  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando
    la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y
    detallando lo mejor posible el funcionamiento técnico de la
    siguiente parte del código:

Método del controlador para la acción de `DELETE`

  - Probar todos los métodos del controlador y hacer captura de pantalla
    de la evidencia obtenida. Esta evidencia debe ser incluida en los
    comentarios del pull request.

**Comment by luzsandobal** [comment]
Adjunto capturas de funcionamiento metodos en Postman
![DELETE-eliminarOK](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/bcbf6e64-bde6-4c27-82d8-94c14d1f4685)
![GET- buscarTodosOk](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/daac398a-ecdf-40b6-af2e-e2cd943d56da)
![GET-buscarPorIdFalla](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/070703e8-699f-47e2-91a3-db60c38ab143)
![GET-buscarPorIdOk](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/37bd6954-ff16-416d-9581-44875957aff5)
![GET-buscarTodos ConError](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/1b18e9cf-dfcc-4ad4-805f-d11204a6720e)
![POST- metodoConError](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/efa57602-7821-46a6-b83f-ccb8743d8373)
![POST-metodoOk](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/f9959170-0ac4-4b3b-a9d9-138214be035f)
![PUT- actualizarOk](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/1c6cffbc-3d77-4f7a-825f-45e15b558ee8)
![PUT-actualizarConError](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/b4571ba4-1fd9-402c-9f41-88b990324fc3)
![DELETE- eliminarError](https://github.com/ahumadamob/imb.pr3.gc.2023.estetica.spring/assets/93212531/ffa9f16c-9ce9-421c-a888-1c20b90bd1fa)

**Comment by ahumadamob** [comment]
No olvides realizar cuanto antes el pull request

**Comment by luzsandobal** [comment]
Listo profe!
