### ISSUE TITLE
Nueva entidad: Método de Pago

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.estetica.spring#2]
Se requiere crear una nueva entidad denominada `MetodoPago` la cual debe contar con los siguientes atributos:

 - id (Integer)
 - nombre (String)
 - habilitado (Boolean)

En el controller, se deben generar los siguientes métodos:
 
 - obtenerMetodosDePago(GET)
 - obtenerMetodosDePagoPorId (GET)
 - crearMetodoPago (POST)
 - modificarMetodoPago (PUT)
 - eliminarMetodoPago (DELETE)

**Comment by ahumadamob** [comment]
En el issue anterior noté que has utilizado una arquitectura diferente y una convención de nombres diferentes a las que venimos utilizando. Por favor, ajusta lo que has aplicado a la issue anterior a esta issue antes de una nueva revisión

**Comment by Luis-Alberto-Espinoza** [comment]
ya esta arreglado. Se elimino tambien desde la interfaz el metodo update.
